### ISSUE TITLE
Failing to ingest data

### ISSUE THREAD

**Issue by saltysalmonella** [ConvoStack/gpt4-chatpdf#1]
I'm running into this error when trying to create the vector store:

> creating vector store...
error [PineconeError: PineconeClient: Error calling upsert: TypeError: stream.getReader is not a function]
/Users/samyang/gpt4-chatpdf/src/embedPdfs.ts:6
import { PineconeStore } from "langchain/vectorstores/pinecone";
                                                                ^
Error: Failed to ingest your data
    at /Users/samyang/gpt4-chatpdf/src/embedPdfs.ts:56:11
    at Generator.throw (<anonymous>)
    at rejected (/Users/samyang/gpt4-chatpdf/src/embedPdfs.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

My pinecone index shows 400 additional vectors, but it is not close to the several thousand there should be.

**Comment by Ryan-Adami** [comment]
What version is your Node. Could be an issue linked to that as described in this thread:

https://community.pinecone.io/t/errorwithoutstacktrace-pineconeclient-error-calling-upsert-typeerror-stream-getreader-is-not-a-function/1008

**Comment by saltysalmonella** [comment]
My node was on 16.19.1 and I updated it to 20.3.0 which seems to have solved that issue, but now I'm running into another issue

> creating vector store...
error [PineconeError: PineconeClient: Error calling upsert: PineconeError: metadata size is 45380 bytes, which exceeds the limit of 40960 bytes per vector]
/Users/samyang/gpt4-chatpdf/src/embedPdfs.ts:6
import { PineconeStore } from "langchain/vectorstores/pinecone";
                                                                ^
Error: Failed to ingest your data
    at /Users/samyang/gpt4-chatpdf/src/embedPdfs.ts:56:11
    at Generator.throw (<anonymous>)
    at rejected (/Users/samyang/gpt4-chatpdf/src/embedPdfs.ts:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Ryan-Adami** [comment]
You need to chunk your metadata. There are restrictions on a per-row level. Try making your document smaller or chunking it.

**Comment by saltysalmonella** [comment]
Issue fixed, seemed to be a problem with one specific pdf I was using, I ran it through an online tool that removed pdf metadata and it now works
